-- (c) Nnachi, Joseph Otu


--DATABASE ASSIGNMENT TASK 2



CREATE TABLE IF NOT EXIST public.Bookings (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY, -- Auto-incrementing primary key
    book_name VARCHAR(100) NOT NULL,
    classification_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    FOREIGN KEY (classification_id) REFERENCES public.classification(classification_id)
);
